language: node_js
node_js:
    - "10"  # nodejs的版本
branches:
    only:
        - web_source  # 设置自动化部署的源码分支

before_install:
    - export TZ='Asia/Shanghai'  # 设置时区
    - npm install hexo-cli -g
    - npm install gulp -g
    - npm install

before_script:
    - git config --global user.name 'Winddoing' #设置github用户名
    - git config --global user.email 'winddoing@sina.cn' #设置github用户邮箱
    - sed -i'' "/^ *repo/s~github\.com~${REPO_TOKEN}@github.com~" _config.yml

install:
    #- npm install --save hexo-generator-searchdb

cache:
    directories:
        - node_modules
script:
    - ./auto_init.sh
    - hexo clean
    - hexo generate
    - gulp

after_success:
    - hexo deploy
    - ./sync_to_coding.sh
