dist: focal
language: node_js

node_js:
    - "14"  # nodejs的版本
branches:
    only:
        - web_source  # 设置自动化部署的源码分支

addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntugis/ppa'
        packages:
            - python3
            - python3-pip
            - fonts-freefont-ttf

python:
    - "3.6.9"

before_install:
    - export TZ='Asia/Shanghai'  # 设置时区
    - npm install

before_script:
    - git config --global user.name 'Winddoing' #设置github用户名
    - git config --global user.email 'winddoing@sina.cn' #设置github用户邮箱
    - sed -i "/^ *repo/s~github\.com~${REPO_TOKEN}@github.com~" _config.yml

install:
    #- npm install --save hexo-generator-searchdb
    - pip3 install pillow

cache:
    directories:
        - node_modules
script:
    - git pull --unshallow
    - ./auto_init.sh
    - hexo generate
    - gulp
    - python3 .gen_watermark.py

after_success:
    - hexo deploy
    #- ./sync_to_coding.sh
