#!/bin/sh

if [ $# != 1 ];then
	echo "usage: $0 "update commit!!!""
	exit 1;
fi

COMMIT=$1

echo "Add all change ...\n"
git add -A

echo "View add results ...\n"
git status

echo "Add commit:<$COMMIT> ...\n"
git commit -m "$COMMIT"

echo "Push to github ...\n"
git push origin web_source
