#!/bin/sh

CUR_TIME=`date`
BRANCH=web_source
REMOTE=origin
COMMIT="$CUR_TIME update branch-$BRANCH"
MANUAL="no"

usage()
{
	echo "usage: $0 -m \"update commit!!!\""
	echo "	-m <commit>"
	echo "	-r <remote>"
	echo "	-b <branch>"
	echo "	-h help"
	echo "	-y Do not manually confirm changes"
	echo ""
	echo "Default config:"
	echo "	--remote:<$REMOTE>"
	echo "	--branch:<$BRANCH>"
	echo ""
	echo "E.g $0 -m \"add a.c\" -r origin -b web_source"

	exit 1;
}

manual_enter(){
	echo -n "Whether submit changes:[yes/y]"
	read enter_x

	while [ x$enter_x != xyes ] && [ x$enter_x != xy ] && [ x$enter_x != x ]
	do
		echo -n "Whether submit changes:[yes/y]"
		read enter_x
	done
}

while getopts b:hm:r:y ops
do
	case $ops in
		b)
			BRANCH=$OPTARG ;;
		r)
			REMOTE=$OPTARG ;;
		m)
			COMMIT=$OPTARG ;;
		y)
			MANUAL="yes" ;;
		h)
			usage ;;
		?)
			usage
			exit 1
		;;
	esac
done


echo "[1]View change file ..."
git status

if [ x$MANUAL != xyes ];then
	manual_enter
else
	echo -n "Whether submit changes:[yes/y] yes"
fi

echo "[2]Add all change ..."
git add -A

echo "[3]Add commit:<$COMMIT> ...\n"
git commit -m "$COMMIT"

echo "[4]Push to github ..."
git push $REMOTE $BRANCH

echo "[5]Submit finish ..."
unset COMMIT BRANCH REMOTE CUR_TIME

exit 1;
